FundingCircle/fc4-framework

README.md
src/fc4c/repl.clj

Non-zero amounts of docs!
Fixes #14.

Some Docs! 🎉

---

.circleci/config.yml
.gitignore
README.md
deps.edn
src/fc4c/clipboard.clj

https://jira.fundingcircle.com/browse/ENG-1482

Measure Test Coverage

---

deps.edn
src/fc4c/integrations/structurizr/express/edit.clj

Fixup deps

---

.circleci/config.yml
src/fc4c/integrations/structurizr/express/clipboard.clj
src/fc4c/integrations/structurizr/express/edit.clj
src/fc4c/integrations/structurizr/express/spec.clj
src/fc4c/model.clj
test/fc4c/test_utils.clj

Apply linter fixes to all src files and add lint step to CI builds

---

src/fc4c/files.clj
src/fc4c/integrations/structurizr/express/spec.clj
src/fc4c/io.clj
src/fc4c/model.clj
src/fc4c/repl.clj
src/fc4c/spec.clj
src/fc4c/util.clj
test/fc4c/io_test.clj
test/fc4c/model_test.clj

As suggested by @fussybeaver in #31. I really like how this moves I/O “to the edges” — or more accurately, isolates it. (“Move I/O to the edges” is advice I’ve seen a few times in the broader Clojure community and I kinda like it as a maxim.)

Isolate I/O

---

src/fc4c/io.clj
src/fc4c/styles.clj
src/fc4c/view_specs.clj
test/data/styles.yaml
test/fc4c/io_test.clj
test/fc4c/styles_test.clj

WRT this comment I added to `io_test.clj`:
> TODO: these are all happy-path tests; some sad-path tests are sorely needed!
I’m going to add these in a follow-up PR soon.

New data structure + file format for FC4 Styles

---

.circleci/config.yml
deps.edn
test/fc4c/test_runner/cloverage.clj

Please see commits.
Before merging:

Faster builds

---

src/fc4c/integrations/structurizr/express/export.clj
src/fc4c/integrations/structurizr/express/spec.clj
test/data/model (valid)/systems/division-a/middle.yaml
test/data/styles (valid).yaml
test/data/views/middle (valid, references undefined system).yaml
test/fc4c/integrations/structurizr/express/export_test.clj

System Context diagrams, specifically. More diagram types coming soon.

Feature: export FC4 views to Structurizr Express diagrams

---

deps.edn

Just for kicks.
FWIW, all the tests pass.

Add a profile that uses prerelease version of Clojure

---

src/main/fc4c/integrations/structurizr/express/edit.clj
src/main/fc4c/integrations/structurizr/express/spec.clj
src/main/fc4c/util.clj

Please see each commit; I recommend reviewing each individually.

Improve readability

---

.circleci/config.yml
tool/Dockerfile
tool/README.md

Please see individual commits.

Misc tweaks to tool

---

.circleci/config.yml

For faster builds.
Also a few tweaks, of course — who can resist?

Trifurcate CI Job

---

.circleci/config.yml
tool/Dockerfile.test
tool/bin/download-clojure-deps
tool/bin/download-pkg-deps
tool/bin/pkg-all
tool/bin/pkg-renderer
tool/bin/pkg-uberjar
tool/bin/tests
tool/bin/tests-with-coverage
tool/deps.edn
tool/dist/fc4
tool/fc4
tool/renderer/render.js
tool/src/cli/fc4/cli/fc4.clj
tool/src/cli/fc4/cli/wcb.clj
tool/src/main/fc4/integrations/structurizr/express/render.clj

Follow-up to #82 and #87. The only thing missing here is updates to the docs; they’re in #89.

Package renderer along with uberjar

---

tool/renderer/render.js

Simon Brown, the owner and maintainer of Structurizr Express, has made some changes to its code that broke our renderer.
Thankfully, he also published [a new example script](https://github.com/structurizr/puppeteer) that demonstrates the optimal way to render and export diagrams via Structurizr Express; this enabled me to both fix our renderer but also improve it.
So this adapts the renderer to the changes but also makes our code simpler and faster.
This required no test changes; the (Clojure) test that invokes the renderer is passing.

Fix + improve automated rendering

---

.circleci/config.yml
.circleci/images/tool/Dockerfile
tool/bin/download-node-deps
tool/bin/pkg-renderer
tool/renderer/package-lock.json
tool/renderer/package.json
tool/renderer/page-functions.js
tool/renderer/render.js

I recommend reviewing each commit individually; they’re fully decoupled. Thanks!

Fix packaged renderer + two other small test/build/package improvements

---

tool/renderer/page-functions.js
tool/renderer/render.js

Please see the individual commits.
Fixes #103
Fixes #104

Fix rendering and improve the renderer’s error-handling

---

tool/doc/examples/docker-install-and-render/Dockerfile
tool/doc/examples/docker-install-and-render/diagram.yaml

Add example Dockerfile that shows how to install fc4-tool and render a diagram

---

tool/deps.edn

[tool] Upgrade to Clojure 1.10

---

.circleci/config.yml
.circleci/images/tool/Dockerfile
tool/Dockerfile.pkg
tool/Dockerfile.test

Update Clojure in builder image to v1.10

---

proposals/README.md
proposals/ep00-enhancement-proposals/ep00-enhancement-proposals.md

Enhancement Proposal EP00: Enhancement Proposals

---

proposals/ep05-new-editing-workflow/ep05-new-editing-workflow.md

I look forward to your comments!

Enhancement Proposal EP05: Unified Authoring Workflow

---

proposals/ep02-automated-rendering/ep02-automated-rendering.md

Enhancement Proposal EP02: Add Automated Rendering to fc4-tool

---

proposals/ep04-initial-ux/ep04-initial-ux.md

Enhancement Proposal EP04: Improve the Initial UX of fc4-tool

---

.circleci/config.yml
tool/renderer/package.json
tool/renderer/render.js

Fixes #147. I suggest reviewing each commit individually. Thank you!

Fix packaging bug that broke rendering

---

tool/src/cli/fc4/cli/edit.clj
tool/src/main/fc4/files.clj
tool/src/main/fc4/io/edit.clj
tool/src/main/fc4/io/render.clj
tool/src/main/fc4/io/util.clj
tool/test/fc4/io/edit_test.clj

I found a bug that I need to fix, but before I fix it I need to add a failing test that will confirm that the fix works (and prevents regressions). Before I do *that* I needed to get the basic scaffolding
in place for testing the CLI workflow, so these commits move the edit CLI workflow into the main codebase and add a test for it.
While that all has intrinsic value, it can also be considered preparatory refactoring for adding that failing test and a fix for it — which I will do in a follow-up branch+PR.
I recommend reviewing each commit individually.
Thanks!

[tool] Test edit CLI workflow

---

tool/src/main/fc4/files.clj
tool/src/main/fc4/io/edit.clj
tool/src/main/fc4/io/util.clj
tool/test/fc4/io/edit_test.clj

The bug and the fix are explained in the commit messages. Reviewers *may* wish to review each commit individually, but there’s some interim changes that are not present in the final diff, so if they’re short on time it’d probably be reasonable to review the combined diff.

Fix Concurrency Bug in Edit Workflow

---

docs/tool/index.md
tool/src/cli/fc4/cli/fc4.clj
tool/src/cli/fc4/cli/format.clj
tool/src/cli/fc4/cli/process.clj
tool/src/cli/fc4/cli/render.clj

To address, at least to some degree, #151.
@Ninju I’d love to get your 👀 on the new subcommands as described in the updated docs, and also the new descriptions of the tool’s main features in the docs. I’m open to any and all feedback but I’m especially interested to know whether these new commands seem useful to you, and whether they make sense.
One thing I’m a little uneasy about is the name of the command _process_ — it just seems super vague and generic. But I couldn’t think of anything better. Please let me know if you have any ideas!
Thanks!

[tool] Add new subcommands: format and process

---

tool/deps.edn
tool/src/main/fc4/integrations/structurizr/express/render.clj
tool/src/main/fc4/io/render.clj
tool/src/main/fc4/rendering.clj
tool/test/fc4/integrations/structurizr/express/render_test.clj
tool/test/fc4/io/render_test.clj

As preparatory refactoring for adding the new Clojure renderer (#155).
I also simplified and streamlined the value returned when an error occurs.
Closes #156

Define Renderer protocol & make Node renderer an implementation of it

---

tool/src/main/fc4/io/edit.clj
tool/test/fc4/io/edit_test.clj

Fix edit bug

---

README.md
docs/index.md

I’m going to demo the framework in an hour here at Write the Docs
Portland 2019 and I want everyone here to feel included in the target
audience!
This is a little bit of an ambitious expansion of the target audience,
but I feel good about it. Ambitious in a good way; I think it’s (mostly)
ready.

Update blurb to add “…and documentarians…” to target audience

---

.circleci/config.yml
.vale.ini
bin/lint-prose
docs/README.md

I was inspired to give this a try by Jodie Putrino’s excellent unconference talk on Vale at Write the Docs Portland 2019.

Use Vale to lint prose

---

.circleci/config.yml
.mdstyle.rb
README.md
bin/lint-markdown
bin/lint-prose
docs/README.md
docs/methodology/authoring_workflow.md
docs/methodology/graphical_notation.md
docs/methodology/publishing.md
docs/methodology/repository.md
docs/methodology/scheme.md
docs/methodology/textual_notation.md
docs/tool/index.md
proposals/ep00-enhancement-proposals/ep00-enhancement-proposals.md
proposals/ep02-automated-rendering/ep02-automated-rendering.md
proposals/ep04-initial-ux/ep04-initial-ux.md
proposals/ep05-new-editing-workflow/ep05-new-editing-workflow.md
tool/README.md

I suggest reviewing each commit individually.
Closes #113!

Lint Markdown!

---

tool/src/main/fc4/io/watch.clj

As per super helpful insight from @alex-steinbaugh in #174 — thanks Alex!!

Minor cleanup of a few comments and docstrings

---

tool/src/main/fc4/io/cli/main.clj

Make the Clojure renderer the default

---

proposals/ep01-decouple-models-and-views-new-dsl/ep01-decouple-models-and-views-new-dsl.md
proposals/ep01-decouple-models-and-views/ep01-decouple-models-and-views.md

Enhancement Proposal EP01: Decoupling Models and Views with a New DSL

---

.circleci/config.yml
tool/bin/install-sys-deps
tool/src/main/fc4/integrations/structurizr/express/chromium_renderer.clj

…to fix bug #236.
I recommend reviewing each commit individually.
@mathpunk I couldn’t assign this PR to you, I guess because you’re not part of the @FundingCircle org, but your feedback on these changes would be most welcome! You can download and test a built installation artifact from [this pre-release](https://github.com/FundingCircle/fc4-framework/releases/tag/prerelease_bug-236).
1. [x] Merge #237
2. [x] Rebase onto master
3. [x] Re-target this PR to master
----
Fixes #236
Blocked by #237

Add support for Arch Linux

---

.github/stale.yml

Stalebot will:
> Automatically close stale Issues and Pull Requests that tend to
> accumulate during a project.
For more info: https://probot.github.io/apps/stale/

Add config file for Stalebot

---

.circleci/bin/create-dist-pkg
.circleci/bin/create-release
.circleci/bin/install-ghr
.circleci/config.yml

More better CI

---

deps.edn
src/fc4/dsl/model.clj
test/fc4/dsl/model_test.clj
test/fc4/test_runner/runner.clj

* Except maybe the first two. The second commit reverts the first, so they sum up to a no-op. I’ve only left them in the branch for historical purposes. Someone searching the commit history at some future point _might_ find those commit messages helpful. Feel free to skip or skim these first two commits.
* Thank you!

Fix long tests redux

---

deps.edn
src/fc4/dsl/model.clj
src/fc4/io/dsl.clj
src/fc4/io/yaml.clj
src/fc4/util.clj
test/data/models/invalid/a/systems/division-a/front.yaml
test/data/models/invalid/a/systems/division-a/middle.yaml
test/data/models/invalid/a/systems/division-b/internal.yaml
test/data/models/invalid/a/systems/division-b/mobile.yaml
test/data/models/invalid/a/systems/external.yaml
test/data/models/invalid/a/users/americas/seller (invalid).yaml
test/data/models/invalid/a/users/dept-that/analyst.yaml
test/data/models/invalid/a/users/dept-this/support.yaml
test/data/models/invalid/a/users/external.yaml
test/data/models/invalid/malformed/malformed.yaml
test/data/models/marketplace/datatypes.yaml
test/data/models/marketplace/systems.yaml
test/data/models/valid/b/single-file/marketplace.yaml
test/data/models/valid/b/split/marketplace/datatypes.yaml
test/data/models/valid/b/split/marketplace/users.yaml
test/fc4/dsl/model_test.clj
test/fc4/io/dsl_test.clj
test/fc4/test_runner/runner.clj

* Thank you!
----
Resolves #232

Functions that validate a model on disk

---

.circleci/bin/halt-if-unchanged

I left some debugging code in there (🤦‍♂) — bc54c75 fixes it.
As long as I was in there I also made a few tweaks. 🙄

Fix CI halt script *again*

---

src/fc4/dsl/model.clj
src/fc4/io/dsl.clj
test/fc4/io/dsl_test.clj

…which was merged earlier this week via #23.
I was reviewing some of this code while resolving some merge conflicts resulting from rebasing a local branch onto master, and I noticed that a few things were off in some of the specs in `src/fc4/dsl/model.clj` and `src/fc4/io/dsl.clj`.
* Thank you!

Fix specs related to loading models
