FundingCircle/fc4-framework

README.md, deps.edn, src/fc4c/cli.clj, src/fc4c/clipboard.clj, src/fc4c/core.clj, src/fc4c/repl.clj, wcb
Simplifies the UX for the most common usage case.
Also moved a bunch of fns from `.repl` to `.clipboard` because it makes more sense now that they’re used by `.cli`.
Refs [ENG-1478](https://jira.fundingcircle.com/browse/ENG-1478)
=> New CLI command: wcb (watch clipboard)

src/fc4c/core.clj, test/fc4c/core_test.clj
One generated, one not.
Increases coverage of core.clj from 86% to 95%.
This *might* fix #16 but I’m not entirely sure — I didn’t have a chance to focus on reproducing that behavior.
=> Add two more tests to increase coverage

README.md, deps.edn, src/fc4c/files.clj, src/fc4c/model.clj, test/data/model/systems/division-a/front.yaml, test/data/model/systems/division-a/middle.yaml, test/data/model/systems/division-b/internal.yaml, test/data/model/systems/division-b/mobile.yaml, test/data/model/systems/external.yaml, test/data/model/users/americas/seller.yaml, test/data/model/users/dept-that/analyst.yaml, test/data/model/users/dept-this/support.yaml, test/data/model/users/external.yaml, test/fc4c/model_test.clj
I know the PR stats make this look big, but it’s mostly test data in YAML files. In terms of code there’s “only” ~240 new lines.
Background from the (private within Funding Circle) ticket:
> Currently with FC4, we have only a single kind of data structure: a diagram. It defines both the systems and their elements and all the relationships thereof, and how those should all be depicted in a specific view.
> 
> This is very straightforward in the sense that we end up with a 1:1 correlation between YAML file and PNG file, and we have only one kind of file/structure: a diagram.
> 
> But! It has a bunch of downsides:
> 
> * Requires lots of duplication and repetition
>   * e.g. a container diagram is a superset of the same system’s context
>     diagram
>   * e.g. the same element may appear in …
=> New data structure/format representing a unified model of all systems and users

.circleci/config.yml, Dockerfile, README.md, deps.edn, src/fc4c/test.clj
Our tests are computationally bound and the prior test runner was
running them sequentially. This is silly, since most machines used by
developers and CI are multi-core. Since [eftest](https://github.com/weavejester/eftest) runs tests across
multiple threads by default, I thought it might work well to address
this — and it does! On my machine, wall-clock time to run the tests
drops from ~66 seconds to ~32 seconds.
I had to upgrade test.check from the latest stable release, 0.9.0, to
the latest alpha release, 0.10.0-alpha3, as there’s some incompatibility
between 0.9.0 and eftest. See https://github.com/weavejester/eftest/issues/32
As long as I was writing custom test running code, I thought I may as
well have it product a JUnit XML file as well, so CircleCI can analyze
and render test …
=>  Switch test runner to eftest for faster tests and builds

src/fc4c/repl.clj
I had moved a function from one namespace to another and forgotten to
add a require of the new namespace, which caused potemkin’s import-vars
to choke on the var I was trying to import, because the new namespace
hadn’t been loaded.
I didn’t notice this so I guess I haven’t been using this namespace
lately, and it has no tests 😬. This was causing the coverage step in
the CI builds to fail, but there’s a `|| true` in the CI command due to
a test that always fails when measuring coverage, for some unknown
reason — see the comment in `.circleci/config.yml` for more. So the only
reason I noticed that the coverage step was failing was because the
CI builds were suddenly much faster — which was nice, actually 😬. I
look forward to integrating the coverage measurement into the
test-running step …
=> Add missing require to fc4c.repl and thereby fix coverage measurements

src/fc4c/integrations/structurizr/express/edit.clj, src/fc4c/integrations/structurizr/express/spec.clj, src/fc4c/io.clj, src/fc4c/model.clj, src/fc4c/spec.clj, src/fc4c/util.clj, src/fc4c/view.clj, src/fc4c/view_specs.clj, test/data/views/middle.yaml, test/fc4c/io_test.clj, test/fc4c/model_test.clj, test/fc4c/util_test.clj, test/fc4c/view_test.clj
Building on 97e611c78 this introduces a new data structure and file
format for defining System Context diagrams and Container diagrams that
can be exported to Structurizr Express (SE) format. After this we just
need a data struct + file format for styles, and then we’ll be able to
move on to exporting these views to SE diagrams.
=> New data structure + file format for FC4 Views

src/fc4c/model.clj, src/fc4c/model_specs.clj
Just as with the view specs in the prior PR (#37), this separation just makes the files easier to read, navigate, etc.
Note to reviewers: the only change herein is to break the specs out of `model.clj` and into `model_specs.cjl`. The contents of the specs haven’t changed at all, so it shouldn’t be necessary to scrutinize the contents of the changed lines.
=> Move model specs into separate file

tool/deps.edn, tool/src/test_utils/fc4/test_runner/runner.clj
I had been hoping to be able to remove the `:multithreading?` option from the eftest config, in the hopes that the default would be simpler, faster, and have lower maintenance implications (cognitive load).
I had thought this might be possible because the latest version of Eftest includes [this fix](https://github.com/weavejester/eftest/pull/58) by @nachomdo.
Unfortunately when I tested the other possible values for `:multithreading?` — including `true` which is the default — the tests took significantly longer to run (on my laptop). I’m not sure why, but regardless, that’s no good.
Given these results, this change ~doesn’t seem to yield any compelling concrete benefits right now~ (update: see below); rather by updating the comment to remove the reference to the bug that Nacho fixed, …
=> Tool: update some test deps

methodology/toolset.md
We have a [direct link](https://github.com/ministryofjustice/laa-architecture-documentation/blob/356c2923f8db2c195487388ff4a54e8e3517efc2/README.md#legal-aid-agency-architecture-documentation) to the https://fundingcircle.github.io/fc4-framework/methodology/toolset.html
page.
New users learn about the "fc4-tool" but cannot see what it is unless they navigate away from the page.
This change adds a link to the directory containing the tool in GitHub to make resolving "fc4-tool" less of a quest for people who are unfamiliar with the framework.
=> Add link to the "fc4-tool" on the "Toolset" page

tool/renderer/.gitignore, tool/renderer/package-lock.json, tool/renderer/package.json, tool/renderer/render.js
This changeset adds a new `renderer` “module” — really just a directory — to fc4-tool. This directory contains `render.js` and everything it needs to function (`package.json` etc). This script implements the approach recommended in #74: it uses Node, Puppeteer, and Chromium to accept a diagram’s YAML representation via stdin, load Structurizr Express (SE) via the Internet, “paste” the diagram YAML representation into SE, trigger the SE “export” feature, and then write the diagram’s PNG image to stdout.
This generally works for me when I test it (manually, on my Mac) using this command from within the `renderer` directory:
```shell
cat ../test/data/structurizr/express/diagram_valid_cleaned.yaml | time ./render.js | open -a Preview.app -f
```
Note that before that’ll work you’ll need to run …
=> Node Renderer

tool/src/main/fc4/integrations/structurizr/express/clipboard.clj, tool/test/fc4/integrations/structurizr/express/clipboard_test.clj
I don’t know why this test failed intermittently, but in looking the
test and its subject over to try to figure it out, I noticed that the
function both returned a value *and* wrote it to stdout as a side effect
which seemed very fuzzy to me, and it looked like this had led to the
test being muddled over what it should be testing — the return value or
the side effect. So I fixed the function by removing the main side
effect and moving it to the function that _calls_ this function.
=> Fix an intermittently failing test

.circleci/config.yml, methodology/authoring_workflow.md, tool/.gitignore, tool/README.md, tool/bin/uberjar, tool/deps.edn, tool/src/cli/fc4/cli/wcb.clj, tool/src/main/fc4/integrations/structurizr/express/clipboard.clj
Fixes #85 which revealed that the tool can’t be compiled on Java 11. This means that the current recommended approach for users to use the tool, by checkout out the source code and running it “from the source” is now [even more](https://github.com/FundingCircle/fc4-framework/pull/76) problematic; it just won’t work if a user has Java 11.
While the project won’t _compile_ on Java 11, once compiled to Java bytecode it will _run_ just fine on Java 11. So I figured: let’s compile in CI, whenever a tag is created/pushed, then create a GitHub “release” and upload the uberjar to the release.
=> Build, package, and deploy an Uberjar artifact containing AOT-compiled code

.circleci/config.yml, .circleci/images/tool/Dockerfile, tool/.dockerignore, tool/Dockerfile.test, tool/bin/download-all-deps, tool/bin/download-clojure-deps, tool/bin/download-node-deps, tool/bin/run, tool/bin/run-all-tests, tool/bin/tests, tool/bin/tests-with-coverage
This is part of the implementation for #74 and a follow-up to #80 and #82.
#82 added a Clojure wrapper and an automated test for the Node renderer added in #80, but wasn’t able to build successfully in CI as the CI build environment needed some updates.
This PR makes those updates, and also leverages those updates to enable running all the tests locally in Docker using the same exact environment and configuration as the CI build environment.
This PR does not include the necessary updates to the docs. Those are coming shortly in a follow-up PR. I kept them separate because _this_ PR is already quite big and I didn’t want this to be too difficult too review.
I’ve realized the above steps won’t work. For an explanation please see the note at the end of the description of #82.
=> Rendering on Alpine

.circleci/config.yml, .circleci/images/tool/Dockerfile, tool/Dockerfile.test, tool/README.md, tool/bin/download-node-deps, tool/renderer/package-lock.json, tool/renderer/package.json, tool/renderer/render.js
This switches our test+build containers from Alpine to Debian Stretch,
which has a more recent version of Chromium. This allows us to upgrade
to a less ancient version of Puppeteer; this less ancient Puppeteer is
compatible with modern Chrome/Chromium. Therefore users no longer need
to have the ancient+obsolete Chrome/Chromium 68 installed on their
systems, which was unlikely, annoying, and insecure.
This also upgrades from Node 10 to Node 11, because why not 😬
Fixes #92
=> Support recent/current versions of Chrome/Chromium

.circleci/config.yml
as prereleases.
This should be helpful for:
* Debugging — sometimes I need to use a built dist package to reproduce some problem so I can debug it
* Enabling users to try out features that are not 100% ready, so we can get feedback sooner rather than later
* Finding out about breakage in the publishing process sooner rather than later
* If a commit/build breaks the publishing process somehow, this way we’ll find out
=> [priority: low] Publish distribution packages for all branch builds

tool/src/cli/fc4/cli/render.clj, tool/src/main/fc4/integrations/structurizr/express/render.clj, tool/src/main/fc4/io.clj, tool/src/main/fc4/io/render.clj, tool/src/main/fc4/spec.clj, tool/test/fc4/integrations/structurizr/express/render_test.clj, tool/test/fc4/io/render_test.clj
Main goal here was to move most functions from `fc4.cli.render` to `fc4.io.render`.
This is preparatory refactoring for EP05 (#111) for which we’ll soon be adding a new `edit` CLI command that will be implemented in `fc4.cli.edit` and will also need to render YAML files. In other words, the functionality that until now was only in fc4.cli.render will need to be used by two different namespaces under fc4.cli, so we needed that functionality to be in a third namespace. (I’m writing in the future tense because that’s what makes sense in the context of this PR but I’ve actually already implemented `fc4.cli.edit` in a “child” branch.)
I chose to move these functions out of the `cli` source tree and into the `main` source tree because by convention we don’t have tests for the code under `cli` …
=> Refactor render namespaces

README.md
This is a follow-up to #142. I used [grip][grip] to preview the markup wherein Markdown was nested
inside HTML, and it rendered just fine. So that situation renders just
fine within github.com, e.g. when viewing the repo or the readme. I had
thought that GitHub Pages used the same Markdown renderer as github.com,
but apparently not — when this was published to [the main FC4 website][home]
the Markdown markup was escaped, not rendered.
Converting the content in the table to HTML should eliminate this problem.
It’s maybe not super-ideal, but table support in Markdown is iffy in
general, so I can live with this. I think it’s an acceptable situation
until we switch the main website to a custom Jekyll theme and I can
start using CSS to lay out the page rather than tables.
[grip]: …
=> [docs] Convert Markdown inside table to HTML

tool/deps.edn, tool/src/main/fc4/image_utils.clj, tool/src/main/fc4/integrations/structurizr/express/chromium_renderer.clj, tool/src/main/fc4/integrations/structurizr/express/node_renderer.clj, tool/src/main/fc4/io/render.clj, tool/src/main/fc4/util.clj, tool/test/fc4/integrations/structurizr/express/chromium_renderer_test.clj, tool/test/fc4/integrations/structurizr/express/node_renderer_test.clj
Background in #155.
This PR adds the Clojure renderer alongside the Node renderer — it’s tested, but it’s not yet user-accessible. That’ll be done next: #159.
Closes #157.
=> Add Clojure Renderer

tool/src/cli/fc4/cli/edit.clj, tool/src/main/fc4/io/edit.clj, tool/src/main/fc4/io/watch.clj, tool/test/data/structurizr/express/se_diagram_invalid_b_formatted_snapped.yaml, tool/test/data/structurizr/express/se_diagram_invalid_d.yaml, tool/test/fc4/io/edit_test.clj, tool/test/fc4/io/watch_test.clj
This is preparatory refactoring for #168.
As part of #168, we’ll be making the watch a mode that’s composable with
the main features, and we’ll be enabling users to toggle each of the
main features individually. In other words, we have three major
features: `-f`, `-s`, and `-r`. A user can invoke the tool with just one of
those — any one, or with any two of them, or with all three. They can
also optionally add `-w` to have the feature(s) applied in “watch mode”.
This is substantially different than the current paradigm, wherein a
specific and limited set of subcommands trigger a hard-coded “workflow”
or mode of operation.
In order to support the new approach, it is necessary to decouple the
watch feature from edit workflow — essentially, to extract the watch
feature from the edit …
=> [tool] Decouple two more features: edit + watch

tool/src/main/fc4/io/cli/main.clj, tool/src/main/fc4/io/render.clj, tool/test/fc4/io/cli/main_test.clj, tool/test/fc4/io/render_test.clj
So as to enable users to opt-in to the experimental (pure Clojure) renderer, as opposed to the default (Node) renderer.
The new renderer itself still has bugs, but that’s expected at this point. In fact, that’s a big motivation for adding this option at this stage: so we can get some help finding bugs.
Closes #159
=> Add CLI option --tmp-renderer

tool/test/fc4/integrations/structurizr/express/chromium_renderer_test.clj, tool/test/fc4/integrations/structurizr/express/node_renderer_test.clj
My initial motivation is to ensure that the new Clojure renderer (#155)
is faster than the current Node renderer. Once we decommission the Node
renderer (#163) these tests will serve as regression tests.
Closes #182
=> Add performance tests for renderers

CHANGES.md, docs/tool/index.md, tool/doc/examples/docker-install-and-render/Dockerfile
We just published a [Homebrew Tap][1] for Funding Circle’s FLOSS tools and [that tap][2] includes a formula for fc4-tool.
This is great because not only does it make it _way_ easier to install the fc4 tool, it also makes it _much_ more likely that users will install updates!
(This _might_ also enable us to get ahold of some download/install stats, but that might require contributing a formula to homebrew-core; I’m not sure.)
[1]: https://docs.brew.sh/Taps
[2]: https://github.com/FundingCircle/homebrew-floss
=> Change recommended installation method to Homebrew

.circleci/config.yml, tool/bin/pkg-all
As per #193.
In addition to hopefully making the Homebrew formula pass `brew audit` ([1](https://github.com/FundingCircle/homebrew-floss/pull/4#issuecomment-521201976)), this may help address https://github.com/FundingCircle/homebrew-floss/issues/6 and https://github.com/FundingCircle/homebrew-floss/issues/7
=> Improve tool versioning scheme

tool/deps.edn, tool/dist/fc4, tool/src/main/fc4/image_utils.clj, tool/src/main/fc4/integrations/structurizr/express/chromium_renderer.clj, tool/test/fc4/integrations/structurizr/express/chromium_renderer_test.clj, tool/test/fc4/integrations/structurizr/express/node_renderer_test.clj, tool/test/fc4/io/cli/main_test.clj, tool/test/fc4/io/render_test.clj
I happened to be scrolling by this code and had a sudden epiphany that
I could just set this system property when launching the JVM instead of
in the code before requiring/importing certain libraries/classes.
So, if this works, this should be nice.
Just for reference, I found this approach to preventing the Java app
icon from popping up and grabbing focus on MacOS [here](https://stackoverflow.com/questions/17460777/stop-java-coffee-cup-icon-from-appearing-in-the-dock-on-mac-osx/17544259#comment48475681_17544259).
=> Small code cleanup related to setting a system property

.circleci/config.yml, tool/Dockerfile.pkg, tool/Dockerfile.test, tool/bin/install-clojure, tool/deps.edn
At first I thought this was going to be simply bumping a few version
numbers, which I do occasionally as a matter of course.
Then I recalled that [a change][1] had recently been made to
clj-chrome-devtools that would enable it to be included as a gitlib
rather than a Maven artifact. I much prefer gitlibs, so I switched it.
Well, that lead to a cascade of changes.
First I ran into [this bug in tools.deps][2] that broke pretty much
everything — but only in CI, not locally. It was pointed out to me in
Clojurians that that bug had already been fixed, so I figured that I
must be using an out-of-date version of Clojure in CI. Sure enough, the
CircleCI Clojure images are fairly out of date and don’t include that
bugfix.
I worked around that by switching from CircleCI’s Clojure images to …
=> Update deps and CI environment

README.md, bin/lint-markdown, bin/lint-prose, contributing.md
I’d thought that internally within Funding Circle we (Product Engineering) were still working with Legal to figure out our guidelines for accepting contributions. But then I recently discovered that  one of our projects ([Jackdaw](https://github.com/FundingCircle/jackdaw/blob/master/CONTRIBUTING.md)) recently started accepting contributions. So I basically just copied these guidelines from that project.
=> Add Developer Certificate of Origin and accept contributions

.github/workflows/code-push.yaml, .github/workflows/docs-push.yaml, tool/deps.edn, tool/dist/fc4
I’m intrigued by the potential of GitHub Actions and want to take some
baby steps into using it.
For now these workflows are mostly redundant with our CircleCI workflow,
but they already have some advantages:
* Actions makes it easy to run one workflow for changes to only a
specific set of files, and a different workflow for changes to a
different set of files. That means that we can run the docs jobs when
the docs change and the code jobs when the code changes — whereas
CircleCI has no built-in support for this sort of thing.
* The syntax for doing “matrix builds” is so much simpler in Actions
than in CircleCI; I’ve been meaning to enable matrix builds in
CircleCI for ages but got stuck in migrating from the 2.0 syntax to
the 2.1; I’m not absolutely sure but this *seems* much simpler in …
=> Add some GitHub Actions CI Workflows

.circleci/bin/install-lint-deps, .circleci/bin/require-java, .circleci/bin/which-os, tool/dist/fc4
Make shell script shebangs consistent
Use `/usr/bin/env` consistently, everywhere.
As per a discussion with @mattsoutherden on commit 9ec9f05f3d6454b565:
He saw that I changed the shebang of a few scripts from
`#!/usr/bin/env bash` to ``#!/bin/bash` and asked:
> Why this change?
>
> I see you're also doing this in `.circleci/bin/require-java `, but not
> elsewhere. Are you specifically targeting the original OS Bash, or
> trying to avoid a different version?
I replied:
> Thanks for asking about this — I kinda had a feeling in my gut that
> this change was ill-considered and half-assed.
>
> As to why, well, I was frustrated by #245 wherein I accidentally broke
> support for Bash 3, which is the default shell on MacOS 10.13 and
> 10.14 (10.15 switched to zsh as the default shell, but it …
=> Make shell script shebangs consistent

tool/test/data/structurizr/express/diagram_valid_expected.svg, tool/test/fc4/integrations/structurizr/express/renderer_test.clj, tool/test/fc4/io/cli/main_test.clj, tool/test/fc4/io/render_test.clj
I was working on something unrelated and the rendering tests started
failing with output like this:
```
expected: (<= distance-percentage (:svg max-allowable-image-differences))
actual: (not (<= 0.052500776638707676 0.05))
```
as you can see, the rendered SVG image was 5.25% different than the
expected image, which exceeded the max allowable difference of 5%.
I took a look and it seems that Simon Brown has made some minor changes
to Structurizr Express’ rendering; mostly to the watermark that
Structurizr Express has been adding to rendered images. Well, actually
he seems to have removed the watermark and replaced it with a larger,
more opaque Structurizr wordmark in a fixed location.
This is of course 100% fine; it’s his product and it’s his prerogative
to change it however he sees fit, …
=> Update tests to handle changes to Structurizr Express

test/fc4/util_test.clj
This test was intermittently failing with output like this:
```
a body that takes longer than the timeout to finish
expected: (thrown? TimeoutException
(u/with-timeout 100 (do (Thread/sleep 150) true)))
actual: nil
```
And sometimes the inverse.
I assume this has something to do with the virtualization setup, or the fact that the MacOS executors on CircleCI are seemingly slow in general.
=> Fix flaky test on MacOS in CircleCI

docs/docs/manual/authoring-workflow.md, docs/docs/manual/graphical-notation.md, docs/docs/manual/index.md, docs/docs/manual/installation.md, docs/docs/manual/publishing.md, docs/docs/manual/repository.md, docs/docs/manual/scheme.md, docs/docs/manual/textual-notation.md, docs/docs/manual/toolset.md, docs/index.md
When I tested the website locally, the absolute links (those starting
with a slash) worked just fine, because in that scenario the site is
“rooted” at the host root — e.g. `docs/manual/scheme.md` is
accessible at `http://localhost:4000/docs/manual/scheme.md` so an
absolute link like `/docs/manual/scheme` works just fine.
When the website is published to GitHub Pages, however, it’s a
[“repo site”][gh-pages-types] — so it’s rooted under a subdirectory,
i.e. there’s an additional segment in the URL, the first one, so
`docs/manual/scheme.md` becomes
`https://fundingcircle.github.io/fc4-framework/docs/manual/scheme.md` so
an absolute link like `/docs/manual/scheme` won’t work — it has to be
relative so that it’ll work in either scenario.
So the links all broke when we merged #257 a few minutes …
=> Website: fix links and redirects

.circleci/bin/halt-if-unchanged, .circleci/config.yml, bin/tests, bin/tests-with-coverage, test/scripts/shutdown-hooks
* Thank you!
I stumbled across [a blog post](https://fant.io/p/circleci-early-exit/) containing a shell script for this purpose, and it looked like a quick, easy, and straightforward way to accomplish this. So I thought I’d give it a try.
This should speed up our CircleCI workflows + pipelines. The early results look good:
Branch | Lint workflow | Test workflow
---- | ---- | -----
[master](https://app.circleci.com/github/FundingCircle/fc4-framework/pipelines?branch=master) | 51s | 9m 14s
[more-faster-ci](https://app.circleci.com/github/FundingCircle/fc4-framework/pipelines?branch=more-faster-ci) | **40s** | **1m 56s**
(I recorded those times when this branch contained only this single commit.)
----
Closes #78
=> More faster CI

.circleci/config.yml
We recently merged #262, which included 7ac35cee3: *Halt CI jobs when no
relevant files have changed.* Which has been working well, except I
noticed that the CircleCI workflows on master, after the PR was merged,
were way too fast.
I thought it over, and I realized that the script halt-if-unchanged will
probably always find no changes when it runs on master — in other words,
on master, it only produces false negatives. I think. It’s a hunch, at
least.
I looked over the source of the script, and I don’t *quite* understand
the script well enough to confirm my hunch. That said, it does seem to
be what’s happening, so I think it’s worth making a small change to
ensure that it doesn’t happen.
I hope this change is fairly self-explanatory, but basically, after
this, any time this job runs on …
=> Fix: CI job publish_dist_pkg never runs on master

.circleci/codecov.yml
I’m still having trouble with Codecov seemingly ignoring this config file. I did some research and these changes *might* help. They aren’t helping with the GitHub “status checks” on *this* commit while in a “feature branch” — but it’s possible that Codecov really only uses the config file that’s in the default branch? I don’t know, I’m baffled and aggravated with Codecov. In a different branch I’m trying out some other services like Coveralls and Code Climate.
=> Attempt to fix Codecov

.circleci/bin/halt-if-unchanged, .circleci/config.yml
This is a follow-up to #266 / 99f481bc1b. In that commit I modified the
CI job publish_dist_pkg to always run on master. Unfortunately I
neglected to do the same for its dependencies: build_dist_pkg and
test_dist_pkg. So publish_dist_pkg did indeed run on master after that
PR was merged, but it failed, because the distribution package hadn’t
been created. Doh!
=> Fix: CI job publish_dist_pkg fails on master

src/fc4/dsl/model.clj, test/fc4/test_runner/runner.clj
We recently re-added these specs, and after they merged to master I
noticed that our CI builds had become significantly slower. So I looked
to make sure that all the collection specs had `:max-gen` specified (the
default is 20, which can be too much for some really sophisticated data
structures) and I found that some had `:max-gen` but some had `:gen-max`
🤦‍♂️
‍This reduces the total time of the tests for this namespace from ~169
seconds to ~67 seconds, a difference of ~102 seconds!
Before:
```
user=> (time (do (println "master") (run-tests 'fc4.dsl.model-test)))
master
Testing fc4.dsl.model-test
Ran 2 tests containing 2 assertions.
0 failures, 0 errors.
"Elapsed time: 169037.62099 msecs"
{:test 2, :pass 2, :fail 0, :error 0, :type :summary}
```
After:
```
user=> (require :reload …
```
=> Fix long tests

README.md
This patch adds the get started and it is nice to have there so that we avoid clicking from the website to the github repo then back to the website.
=> Add Get Started section to the README

README.md, docs/index.md
I happened to notice that this “documentarians” wasn’t a hyperlink, which is not great because it’s not a common term.
=> Docs: add missing link
